services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhinav2005
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    environment:
      - PORT=5000
      - PG_USER=postgres
      - PG_PASSWORD=abhinav2005
      - PG_DATABASE=todoapp
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:
